### ISSUE TITLE
entropy.seg & the js.div.seg function Warning messages ...

### ISSUE THREAD

**Issue by drkoryjohns** [imminfo/tcr#11]
Hello,

In attempting to run the entropy.seg function, I am encountering the below Warning message:

"Sum of the input vector is NOT equal to 1. Function may produce incorrect results.
To fix this try to set .do.norm = TRUE in the function's parameters."

When exploring the options I can pass to the entropy.seg function, the .do.norm parameter is not a definable option by the user.

When I explore the code for the entropy.seg function, I see the entropy function call within the higher entropy.seg function.  When I attempt to add the .do.norm = T option to the entropy function call within the entropy.seg function, the Message still persists?

The Warning message also occurs when I attempt to use the js.div.seg function.

Need resolution please.

Thank you ... best,

Kory

**Comment by vadimnazarov** [comment]
Hello,

My first guess that there is something with R and how it's normalise numeric vectors. Sometimes after normalisation `sum(x / sum(x))` is not equal to 1. I know because I also get this warning sometimes and checked the case with the sum. So I think you could just leave it like this with warnings and get correct results despite of the warning.

May I ask you to send me the vector with quantities (Read.count / Read.proportion / Umi etc.) that you use to compute gene segment distribution entropy please so I can check it on my machine? You could use https://gist.github.com - just paste the vector there and copy link to it here.
