### ISSUE TITLE
function js.div.seg - additional parameter for .do.norm

### ISSUE THREAD

**Issue by kvanhoorde** [imminfo/tcr#49]
Is it possible to create an additional parameter in this function: .do.norm? Currently it is not possible to specify .do.norm = TRUE when calling the entropy function. (Although you might get the suggestion from the function check.distribution.)

**Comment by vadimnazarov** [comment]
I was thinking that because .do.norm by default is NA it means that `js.div.seg` checks for distribution internally. Do you have cases where you need to force .do.norm? I can't find any cases.

As a side note, there is no `.laplace` parameter in js.div.seg, so it might be useful to add this, may be it is what you need?

**Comment by vadimnazarov** [comment]
Hi, tcR package is no longer supported and current issues will not be fixed. A new package is available that is designed to replace tcR called immunarch. We have solved most of the problems tcR package had and improved the overall pipeline, providing functions for painless repertoire file parsing and publication-ready plot making. 

The mission of the immunarch is to make immune repertoire data analysis as easy and possible—even with R. Please feel free to check it here: https://immunarch.com/

If you have any suggestions, bugs, improvements, etc. -- please write us or create an issue in https://github.com/immunomind/immunarch/issues

Thank you! Sincerely,
immunarch dev team and Vadim I. Nazarov, lead developer
